services:
  expense-approval:
    container_name: expense-approval
    "build": {
      "dockerfile": "Dockerfile"
    }
    ports:
      - "9002:9002"  # for PHP-FPM
      - "44857:44857"  # for Xdebug
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=44857
    volumes:
      - ./expense-approval:/var/www/html/
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      sh -c "composer install &&
      php artisan serve --host=0.0.0.0 --port=9002"
      rm public/storage
      php artisan storage:link
      ls -l public/storage
    networks:
        - expense-approval-network
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - expense-approval-network
  expense-approval-mysql:
    image: mysql:5.7
    container_name: expense-approval-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - expense-approval-network
  expense-approval-vite:
    container_name: expense-approval-vite
    image: node:20  # Official Node.js image with npm pre-installed
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./expense-approval:/var/www/html  # Mount your project
      - /var/www/html/node_modules        # Isolate node_modules from the host
    command: >
      sh -c "npm install && npm run dev"  # Install deps and start Vite
    networks:
      - expense-approval-network
networks:
  expense-approval-network:
    driver: bridge